### ISSUE TITLE
Exception encountered in

### ISSUE THREAD

**Issue by tumasov69** [GemstoneGG/Velocity-CTD#518]
### Expected Behavior

[22:41:18 ERROR]: [server connection] ulanovlesa344 -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@345f8806
io.netty.util.IllegalReferenceCountException: null
        at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.rootParent(AdaptivePoolingAllocator.java:1008) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.memoryAddress(AdaptivePoolingAllocator.java:1079) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:355) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:779) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.handle(AbstractEpollChannel.java:471) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.epoll.EpollIoHandler$DefaultEpollIoRegistration.handle(EpollIoHandler.java:307) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.epoll.EpollIoHandler.processReady(EpollIoHandler.java:489) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.epoll.EpollIoHandler.run(EpollIoHandler.java:444) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:204) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:175) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
        at com.velocitypowered.proxy.util.concurrent.VelocityNettyThreadFactory$1.run(VelocityNettyThreadFactory.java:45) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]

### Actual Behavior

The player was just standing and hitting mobs, and for some reason, they got kicked from the server.

### Steps to Reproduce

# Config version. Do not change this
config-version = "2.7"

# What port should the proxy be bound to? By default, we'll bind to all addresses on port 25565.
bind = "0.0.0.0:25565"

# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Only MiniMessage format is accepted.
motd = "     <green><bold>Realms MC</bold> <dark_gray><bold><obfuscated>|</obfuscated></bold><aqua> 1.16.5-1.21.5 <dark_gray><bold><obfuscated>|</obfuscated></bold><white> mc.realmsmc.ru <dark_gray><bold><obfuscated>|</obfuscated></bold>               <bold><white>➤</bold> <white>У нас открылся <green>Ванильный <white>режим"

# What should we display for the maximum number of players? (Velocity does not support a cap
# on the number of players online.)
show-max-players = 500

# Should we authenticate players with Mojang? By default, this is on.
online-mode = false

# Should the proxy enforce the new public key security standard? By default, this is on.
force-key-authentication = true

# If client's ISP/AS sent from this proxy is different from the one from Mojang's
# authentication server, the player is kicked. This disallows some VPN and proxy
# connections but is a weak form of protection.
prevent-client-proxy-connections = false

# Should we forward IP addresses and other data to backend servers?
# Available options:
# - "none":        No forwarding will be done. All players will appear to be connecting
#                  from the proxy and will have offline-mode UUIDs.
# - "legacy":      Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
#                  if you run servers using Minecraft 1.12 or lower.
# - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard
#                  plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
#                  unable to implement network level firewalling (on a shared host).
# - "modern":      Forward player IPs and UUIDs as part of the login process using
#                  Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
player-info-forwarding-mode = "modern"

# If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
# The file is expected to be UTF-8 encoded and not empty.
forwarding-secret-file = "forwarding.secret"

# Announce whether or not your server supports Forge. If you run a modded server, we
# suggest turning this on.
# 
# If your network runs one modpack consistently, consider using ping-passthrough = "mods"
# instead for a nicer display in the server list.
announce-forge = false

# If enabled (default is false) and the proxy is in online mode, Velocity will kick
# any existing player who is online if a duplicate connection attempt is made.
kick-existing-players = false

# Should Velocity pass server list ping requests to a backend server?
# Available options:
# - "disabled":    No pass-through will be done. The velocity.toml and server-icon.png
#                  will determine the initial server list ping response.
# - "mods":        Passes only the mod list from your backend server into the response.
#                  The first server in your try list (or forced host) with a mod list will be
#                  used. If no backend servers can be contacted, Velocity won't display any
#                  mod information.
# - "description": Uses the description and mod list from the backend server. The first
#                  server in the try (or forced host) list that responds is used for the
#                  description and mod list.
# - "all":         Uses the backend server's response as the proxy response. The Velocity
#                  configuration is used if no servers could be contacted.
ping-passthrough = "DISABLED"

# If not enabled (default is true) player IP addresses will be replaced by <ip address withheld> in logs
enable-player-address-logging = true

[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
lobby = "127.0.0.1:30066"
vanilla = "127.0.0.1:30067"
survival = "127.0.0.1:30070"
kitpvp = "127.0.0.1:30069"

# In what order we should try servers when a player logs in or is kicked from a server.
try = [
    "lobby"
]

[forced-hosts]
# Configure your forced hosts here.
"lobby.example.com" = [
    "lobby"
]
"vanilla.example.com" = [
    "vanilla"
]
"survival.example.com" = [
    "survival"
]
"kitpvp.example.com" = [
    "kitpvp"
]

[advanced]
# How large a Minecraft packet has to be before we compress it. Setting this to zero will
# compress all packets, and setting it to -1 will disable compression entirely.
compression-threshold = 256

# How much compression should be done (from 0-9). The default is -1, which uses the
# default level of 6.
compression-level = -1

# How fast (in milliseconds) are clients allowed to connect after the last connection? By
# default, this is three seconds. Disable this by setting this to 0.
login-ratelimit = 3000

# Specify a custom timeout for connection timeouts here. The default is five seconds.
connection-timeout = 10000

# Specify a read timeout for connections here. The default is 30 seconds.
read-timeout = 10000

# Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is for, then
# don't enable it.
haproxy-protocol = false

# Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
tcp-fast-open = false

# Enables BungeeCord plugin messaging channel support on Velocity.
bungee-plugin-message-channel = true

# Shows ping requests to the proxy from clients.
show-ping-requests = false

# By default, Velocity will attempt to gracefully handle situations where the user unexpectedly
# loses connection to the server without an explicit disconnect message by attempting to fall the
# user back, except in the case of read timeouts. BungeeCord will disconnect the user instead. You
# can disable this setting to use the BungeeCord behavior.
failover-on-unexpected-server-disconnect = true

# Declares the proxy commands to 1.13+ clients.
announce-proxy-commands = true

# Enables the logging of commands
log-command-executions = false

# Enables logging of player connections when connecting to the proxy, switching servers
# and disconnecting from the proxy.
log-player-connections = true

# Allows players transferred from other hosts via the
# Transfer packet (Minecraft 1.20.5) to be received.
accepts-transfers = false

[query]
# Whether to enable responding to GameSpy 4 query responses or not.
enabled = false

# If query is enabled, on what port should the query protocol listen on?
port = 25565

# This is the map name that is reported to the query services.
map = "Velocity"

# Whether plugins should be shown in query response by default or not
show-plugins = false

### Plugin List

floodgate-velocity, Geyser-Velocity, limboapi-1.1.27-SNAPSHOT, LimboAuth Social Addon-1.0.11-SNAPSHOT, limboauth-1.1.14, LimboReconnect-1.1.5, LiteBans, LuckPerms-Velocity-5.4.153, PlasmoVoice-Velocity-2.1.3, SkinsRestorer, snap, velocity-tools-1.2.4

### Velocity Version

Velocity 3.4.0-SNAPSHOT (git-88211b7b)

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> [22:41:18 ERROR]: [server connection] ulanovlesa344 -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@345f8806 io.netty.util.IllegalReferenceCountException: null at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.rootParent(AdaptivePoolingAllocator.java:1008) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.memoryAddress(AdaptivePoolingAllocator.java:1079) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:355) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:779) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.handle(AbstractEpollChannel.java:471) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.epoll.EpollIoHandler$DefaultEpollIoRegistration.handle(EpollIoHandler.java:307) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.epoll.EpollIoHandler.processReady(EpollIoHandler.java:489) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.epoll.EpollIoHandler.run(EpollIoHandler.java:444) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:204) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:175) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)] at com.velocitypowered.proxy.util.concurrent.VelocityNettyThreadFactory$1.run(VelocityNettyThreadFactory.java:45) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
> 
> ### Actual Behavior
> The player was just standing and hitting mobs, and for some reason, they got kicked from the server.
> 
> ### Steps to Reproduce
> # Config version. Do not change this
> config-version = "2.7"
> 
> # What port should the proxy be bound to? By default, we'll bind to all addresses on port 25565.
> bind = "0.0.0.0:25565"
> 
> # What should be the MOTD? This gets displayed when the player adds your server to
> # their server list. Only MiniMessage format is accepted.
> motd = " Realms MC <dark_gray>| 1.16.5-1.21.5 <dark_gray>| mc.realmsmc.ru <dark_gray>| ➤ У нас открылся Ванильный режим"
> 
> # What should we display for the maximum number of players? (Velocity does not support a cap
> # on the number of players online.)
> show-max-players = 500
> 
> # Should we authenticate players with Mojang? By default, this is on.
> online-mode = false
> 
> # Should the proxy enforce the new public key security standard? By default, this is on.
> force-key-authentication = true
> 
> # If client's ISP/AS sent from this proxy is different from the one from Mojang's
> # authentication server, the player is kicked. This disallows some VPN and proxy
> # connections but is a weak form of protection.
> prevent-client-proxy-connections = false
> 
> # Should we forward IP addresses and other data to backend servers?
> # Available options:
> # - "none": No forwarding will be done. All players will appear to be connecting
> # from the proxy and will have offline-mode UUIDs.
> # - "legacy": Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
> # if you run servers using Minecraft 1.12 or lower.
> # - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard
> # plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
> # unable to implement network level firewalling (on a shared host).
> # - "modern": Forward player IPs and UUIDs as part of the login process using
> # Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
> player-info-forwarding-mode = "modern"
> 
> # If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
> # The file is expected to be UTF-8 encoded and not empty.
> forwarding-secret-file = "forwarding.secret"
> 
> # Announce whether or not your server supports Forge. If you run a modded server, we
> # suggest turning this on.
> # If your network runs one modpack consistently, consider using ping-passthrough = "mods"
> # instead for a nicer display in the server list.
> announce-forge = false
> 
> # If enabled (default is false) and the proxy is in online mode, Velocity will kick
> # any existing player who is online if a duplicate connection attempt is made.
> kick-existing-players = false
> 
> # Should Velocity pass server list ping requests to a backend server?
> # Available options:
> # - "disabled": No pass-through will be done. The velocity.toml and server-icon.png
> # will determine the initial server list ping response.
> # - "mods": Passes only the mod list from your backend server into the response.
> # The first server in your try list (or forced host) with a mod list will be
> # used. If no backend servers can be contacted, Velocity won't display any
> # mod information.
> # - "description": Uses the description and mod list from the backend server. The first
> # server in the try (or forced host) list that responds is used for the
> # description and mod list.
> # - "all": Uses the backend server's response as the proxy response. The Velocity
> # configuration is used if no servers could be contacted.
> ping-passthrough = "DISABLED"
> 
> # If not enabled (default is true) player IP addresses will be replaced by in logs
> enable-player-address-logging = true
> 
> [servers]
> 
> # Configure your servers here. Each key represents the server's name, and the value
> # represents the IP address of the server to connect to.
> lobby = "127.0.0.1:30066" vanilla = "127.0.0.1:30067" survival = "127.0.0.1:30070" kitpvp = "127.0.0.1:30069"
> 
> # In what order we should try servers when a player logs in or is kicked from a server.
> try = [ "lobby" ]
> 
> [forced-hosts]
> 
> # Configure your forced hosts here.
> "lobby.example.com" = [ "lobby" ] "vanilla.example.com" = [ "vanilla" ] "survival.example.com" = [ "survival" ] "kitpvp.example.com" = [ "kitpvp" ]
> 
> [advanced]
> 
> # How large a Minecraft packet has to be before we compress it. Setting this to zero will
> # compress all packets, and setting it to -1 will disable compression entirely.
> compression-threshold = 256
> 
> # How much compression should be done (from 0-9). The default is -1, which uses the
> # default level of 6.
> compression-level = -1
> 
> # How fast (in milliseconds) are clients allowed to connect after the last connection? By
> # default, this is three seconds. Disable this by setting this to 0.
> login-ratelimit = 3000
> 
> # Specify a custom timeout for connection timeouts here. The default is five seconds.
> connection-timeout = 10000
> 
> # Specify a read timeout for connections here. The default is 30 seconds.
> read-timeout = 10000
> 
> # Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is for, then
> # don't enable it.
> haproxy-protocol = false
> 
> # Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
> tcp-fast-open = false
> 
> # Enables BungeeCord plugin messaging channel support on Velocity.
> bungee-plugin-message-channel = true
> 
> # Shows ping requests to the proxy from clients.
> show-ping-requests = false
> 
> # By default, Velocity will attempt to gracefully handle situations where the user unexpectedly
> # loses connection to the server without an explicit disconnect message by attempting to fall the
> # user back, except in the case of read timeouts. BungeeCord will disconnect the user instead. You
> # can disable this setting to use the BungeeCord behavior.
> failover-on-unexpected-server-disconnect = true
> 
> # Declares the proxy commands to 1.13+ clients.
> announce-proxy-commands = true
> 
> # Enables the logging of commands
> log-command-executions = false
> 
> # Enables logging of player connections when connecting to the proxy, switching servers
> # and disconnecting from the proxy.
> log-player-connections = true
> 
> # Allows players transferred from other hosts via the
> # Transfer packet (Minecraft 1.20.5) to be received.
> accepts-transfers = false
> 
> [query]
> 
> # Whether to enable responding to GameSpy 4 query responses or not.
> enabled = false
> 
> # If query is enabled, on what port should the query protocol listen on?
> port = 25565
> 
> # This is the map name that is reported to the query services.
> map = "Velocity"
> 
> # Whether plugins should be shown in query response by default or not
> show-plugins = false
> 
> ### Plugin List
> floodgate-velocity, Geyser-Velocity, limboapi-1.1.27-SNAPSHOT, LimboAuth Social Addon-1.0.11-SNAPSHOT, limboauth-1.1.14, LimboReconnect-1.1.5, LiteBans, LuckPerms-Velocity-5.4.153, PlasmoVoice-Velocity-2.1.3, SkinsRestorer, snap, velocity-tools-1.2.4
> 
> ### Velocity Version
> Velocity 3.4.0-SNAPSHOT (git-88211b7b)
> 
> ### Additional Information
> _No response_

Ensure you're using the very latest build of CTD. This issue is resolved. Additionally, regenerate your `lang` folder and `velocity.toml`. If you use Pterodactyl, your `velocity.toml` may not properly regenerate. Here's the raw configuration, here: https://github.com/GemstoneGG/Velocity-CTD/blob/libdeflate/proxy/src/main/resources/default-velocity.toml

**Comment by tumasov69** [comment]
[23:39:45] [Netty epoll Worker #27/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] 12461246 (/95.58.205.255:50470) has disconnected: An internal error occurred in your connection.
[23:39:45] [Netty epoll Worker #27/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] 12461246 (/95.58.205.255:50470): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@7dcc7ea5
io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:830) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:755) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:830) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:755) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1036) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.Channel.write(Channel.java:267) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:258) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:463) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:167) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:58) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:68) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1429) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:793) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.handle(AbstractEpollChannel.java:471) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.epoll.EpollIoHandler$DefaultEpollIoRegistration.handle(EpollIoHandler.java:307) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.epoll.EpollIoHandler.processReady(EpollIoHandler.java:489) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.epoll.EpollIoHandler.run(EpollIoHandler.java:444) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:204) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:175) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.util.concurrent.VelocityNettyThreadFactory$1.run(VelocityNettyThreadFactory.java:45) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
Caused by: io.netty.util.IllegalReferenceCountException
	at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.rootParent(AdaptivePoolingAllocator.java:1008) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.alloc(AdaptivePoolingAllocator.java:1048) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:302) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.buffer.AbstractByteBuf.writeMedium(AbstractByteBuf.java:1007) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.protocol.ProtocolUtils.write21BitVarInt(ProtocolUtils.java:224) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.handleCompressed(MinecraftCompressorAndLengthEncoder.java:60) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.encode(MinecraftCompressorAndLengthEncoder.java:52) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.encode(MinecraftCompressorAndLengthEncoder.java:33) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server.jar:3.4.0-SNAPSHOT (git-88211b7b)]
	... 37 more

**Comment by tumasov69** [comment]
[19:23:38] [Netty epoll Worker #37/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] egor310812 -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@a9df01c
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:101) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1429) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:793) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.handle(AbstractEpollChannel.java:471) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.epoll.EpollIoHandler$DefaultEpollIoRegistration.handle(EpollIoHandler.java:307) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.epoll.EpollIoHandler.processReady(EpollIoHandler.java:489) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.epoll.EpollIoHandler.run(EpollIoHandler.java:444) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:204) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:175) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1073) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at com.velocitypowered.proxy.util.concurrent.VelocityNettyThreadFactory$1.run(VelocityNettyThreadFactory.java:45) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
Caused by: io.netty.util.IllegalReferenceCountException
	at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.rootParent(AdaptivePoolingAllocator.java:1008) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.alloc(AdaptivePoolingAllocator.java:1048) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:302) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at com.velocitypowered.natives.compression.LibdeflateVelocityCompressor.inflate(LibdeflateVelocityCompressor.java:54) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:72) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder.decode(MinecraftCompressDecoder.java:34) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:91) ~[server.jar:3.4.0-SNAPSHOT (git-6207ace2)]
	... 18 more

**Comment by R00tB33rMan** [comment]
I don’t believe this issue is valid anymore. I’ve merged Velocity’s confirmed fix for this which is no longer creating issues for me.

**Comment by tumasov69** [comment]
I am using the latest version of Velocity-CTD, and literally everyone just got kicked out with this error.

https://mclo.gs/FMCfece

**Comment by R00tB33rMan** [comment]
> I am using the latest version of Velocity-CTD, and literally everyone just got kicked out with this error.
> 
> https://mclo.gs/FMCfece

Have you determined if this occurs under regular Velocity? I've had some other users report this issue and I personally cannot reproduce this. Additionally, a lot of networks (including ones like ManaCube) have encountered severe exploitation recently that I have yet to reproduce due to various upstream fixes.

**Comment by R00tB33rMan** [comment]
> I am using the latest version of Velocity-CTD, and literally everyone just got kicked out with this error.
> 
> https://mclo.gs/FMCfece

Can you try the latest JAR? If my latest JAR resolves your issues, then it was a regular-Velocity issue and not us (that I managed to patch).

**Comment by bobhenl** [comment]
I can confirm, I use build from 18/04 and it's still happening
[06:40:36] [main/INFO] [com.velocitypowered.proxy.VelocityServer]: Booting up Velocity 3.4.0-SNAPSHOT (git-17120a63)...

**Comment by bobhenl** [comment]
Using normal velocity latest it works there, so it's something in Velocity CTD, I've switched for now till it's solved

**Comment by HonzasikCZ** [comment]
I have same problem with velocity CTD version: 3.4.0-SNAPSHOT (git-82a91fe0)
Plugins: packetevents, antihealthindicator, commandwhitelist, deluxemotd, luckperms, foxgate, jpremium, nuvotifier, playercrasher, premiumvanish, skinsrestorer, sonar

**Comment by HonzasikCZ** [comment]
I'm sorry, the problem was somewhere else

**Comment by R00tB33rMan** [comment]
This issue is not **fully** related to CTD and has been effectively resolved. Velocity has an issue that's open in relation. Cannot reproduce since reversions.
